SELECT a.PRODUCT_CODE
     , SUM(a.PRICE * b.SALES_AMOUNT) as SALES
  FROM PRODUCT a
  INNER JOIN OFFLINE_SALE b on b.PRODUCT_ID = a.PRODUCT_ID
GROUP BY
       a.PRODUCT_CODE
ORDER BY
       2 desc
     , 1