WITH RENTED AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE to_date('20221016', 'yyyymmdd') between trunc(START_DATE) and trunc(END_DATE)
)
SELECT
    CAR_ID,
    CASE
        WHEN CAR_ID IN (SELECT CAR_ID FROM RENTED)
        THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM (
    SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) ALL_CARS
ORDER BY CAR_ID DESC;