SELECT b.INGREDIENT_TYPE
     , sum(a.TOTAL_ORDER) as TOTAL_ORDER
  FROM FIRST_HALF a
  INNER JOIN ICECREAM_INFO b ON b.FLAVOR = a.FLAVOR
 WHERE 1=1
GROUP BY
        b.INGREDIENT_TYPE
ORDER BY
        2