SELECT a.CATEGORY
     , sum(b.SALES) as TOTAL_SALES
  FROM BOOK a
  INNER JOIN BOOK_SALES b ON b.BOOK_ID = a.BOOK_ID
 WHERE 1=1
   AND to_char(b.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY
       a.CATEGORY
ORDER BY
       1